### ISSUE TITLE
Error: cannot be provided without an @Provides-annotated method.

### ISSUE THREAD

**Issue by imran855** [abhriyaroy/Modular-Navigation-Theming#1]
I am getting this error while building my application. I follow your architecture. Could you please help me with this?

**Comment by abhriyaroy** [comment]
Hey, I tried to clone this project and make a build, and it worked fine. Can you please paste the entire error log you are getting?

**Comment by imran855** [comment]
Thanks for your quick reply. Actually, I using a dynamic feature module. I have tested hilt and dagger 2 but I am facing the same error. Anyway, I like your project architecture and I want to implement like this way.

**Comment by abhriyaroy** [comment]
Okay so from what I get you are using this same architecture in a different codebase, so I dont know if opening this ticket here will help you. But however, please make sure that the dependencies you are injectng are actually provided by using an @provides method before calling inject on them.
